"""
Django settings for bearcreek project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import date
from decimal import Decimal
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-%2@1#%hkir+yn)^aif(p2v!&@(99i#j^zkmqsl^*1d9n%e19%d')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF trusted origins for Render deployment
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://bcapiaries.com',
    'https://www.bcapiaries.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'storages',  # django-storages for S3
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bearcreek.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'shop.context_processors.promo_banner',
            ],
        },
    },
]

WSGI_APPLICATION = 'bearcreek.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Use persistent disk path on Render, fallback to local for development

if os.getenv('RENDER'):
    # Render deployment - use persistent disk
    DB_PATH = Path('/opt/render/project/src/data/db.sqlite3')
else:
    # Local development
    DB_PATH = BASE_DIR / 'db.sqlite3'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# =============================================================================
# Media Files (User uploaded files - Product images, etc.)
# =============================================================================

# Use S3 in production, local storage in development
if os.getenv('USE_S3', 'False').lower() == 'true':
    # AWS S3 Settings for Production
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')

    # S3 file settings
    AWS_S3_FILE_OVERWRITE = False  # Don't overwrite files with same name
    AWS_DEFAULT_ACL = None  # Use bucket default ACL
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # Cache for 1 day
    }
    AWS_QUERYSTRING_AUTH = False  # Public URLs (no signed URLs)

    # Use S3 for media files
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/'
else:
    # Local storage for development
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# Security Settings (for production)
# =============================================================================

# HTTPS/SSL Settings - Enable these in production
if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Secure cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HTTP Strict Transport Security
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Prevent content type sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # XSS Protection
    SECURE_BROWSER_XSS_FILTER = True

    # Clickjacking protection
    X_FRAME_OPTIONS = 'DENY'

# =============================================================================
# Email Settings (for notifications)
# =============================================================================

# For development, use console backend (prints to terminal)
# For production, configure SMTP
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@bcapiaries.com')

# Admin email notification (optional fallback)
ADMIN_NOTIFICATION_EMAIL = os.getenv('ADMIN_NOTIFICATION_EMAIL', '' if DEBUG else 'tarivan60@gmail.com')

# =============================================================================
# Slack Notifications
# =============================================================================

# Incoming webhook URL from Slack App settings → Incoming Webhooks
SLACK_WEBHOOK_URL = os.getenv('SLACK_WEBHOOK_URL', '')

# Two-way Slack (reactions update order/request status). When the bot token +
# channel are set, notifications post via chat.postMessage (capturing the
# message ts) instead of the outbound-only webhook.
#   SLACK_BOT_TOKEN      — bot user OAuth token (xoxb-…), scopes: chat:write, reactions:read
#   SLACK_SIGNING_SECRET — verifies inbound Events API requests at /slack/events/
#   SLACK_CHANNEL        — channel id/name the bot posts notifications to
#   SLACK_ALLOWED_REACTORS — optional comma-separated Slack user IDs allowed to
#                            drive status changes (empty = anyone in the channel)
SLACK_BOT_TOKEN = os.getenv('SLACK_BOT_TOKEN', '')
SLACK_SIGNING_SECRET = os.getenv('SLACK_SIGNING_SECRET', '')
SLACK_CHANNEL = os.getenv('SLACK_CHANNEL', '')
SLACK_ALLOWED_REACTORS = [
    u.strip() for u in os.getenv('SLACK_ALLOWED_REACTORS', '').split(',') if u.strip()
]

# =============================================================================
# Google Maps (Places Autocomplete on address fields)
# =============================================================================

GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY', '')

# =============================================================================
# Seasonal promo banner
# =============================================================================
# Date-gated so the promotion retires itself with no manual teardown: the banner
# only renders while today is within [START, END] (inclusive). Override the
# window with the env vars (YYYY-MM-DD); set PROMO_BANNER_END empty to disable.


def _parse_promo_date(value):
    try:
        return date.fromisoformat(value) if value else None
    except ValueError:
        return None


PROMO_BANNER_START = _parse_promo_date(os.getenv('PROMO_BANNER_START', '2026-06-29'))
PROMO_BANNER_END = _parse_promo_date(os.getenv('PROMO_BANNER_END', '2026-07-05'))
# Per-jar discount advertised during the promo. Display-only: the figure is
# shown to customers and applied by hand on the QuickBooks invoice (the site
# takes no online payment), so no stored order total is recomputed.
PROMO_DISCOUNT_PER_JAR = Decimal(os.getenv('PROMO_DISCOUNT_PER_JAR', '2'))
