# Generated by Django 6.0 on 2025-12-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, help_text='QuickBooks Payment Link', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qb_invoice_id',
            field=models.CharField(blank=True, help_text='QuickBooks Invoice ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qb_payment_id',
            field=models.CharField(blank=True, help_text='QuickBooks Payment ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
