# Generated by Django 6.0 on 2026-01-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_paid_at_order_payment_status_order_payment_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeeRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('property_address', models.TextField(help_text='Address where bees are located')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='FL', max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural/Farm'), ('other', 'Other')], default='residential', max_length=20)),
                ('bee_location', models.CharField(choices=[('tree', 'Tree/Branch'), ('wall', 'Inside Wall'), ('roof', 'Roof/Eaves'), ('ground', 'Ground/Underground'), ('shed', 'Shed/Outbuilding'), ('fence', 'Fence Post'), ('other', 'Other')], max_length=50)),
                ('bee_location_other', models.CharField(blank=True, help_text="If 'Other', please describe", max_length=100)),
                ('how_long_present', models.CharField(help_text="How long have the bees been there? (e.g., 'Just noticed today', '1 week', 'Several months')", max_length=100)),
                ('estimated_size', models.CharField(blank=True, help_text="Approximate size of the swarm/colony (e.g., 'softball size', 'basketball size', 'large colony')", max_length=100)),
                ('height_from_ground', models.CharField(blank=True, help_text="Approximate height from ground (e.g., '6 feet', '15 feet', 'ground level')", max_length=50)),
                ('urgency', models.CharField(choices=[('low', 'Low - No immediate concern'), ('medium', 'Medium - Would like removed soon'), ('high', 'High - Causing problems, need quick response'), ('emergency', 'Emergency - Safety concern')], default='medium', max_length=20)),
                ('has_been_sprayed', models.BooleanField(default=False, help_text='Have the bees been sprayed with pesticides?')),
                ('can_send_photo', models.BooleanField(default=False, help_text='Are you able to send photos of the bees?')),
                ('notes', models.TextField(blank=True, help_text='Any additional information that might help us')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bee Removal Request',
                'verbose_name_plural': 'Bee Removal Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollinationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('property_address', models.TextField(help_text='Address where pollination services are needed')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='FL', max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('crop_type', models.CharField(choices=[('citrus', 'Citrus'), ('blueberries', 'Blueberries'), ('watermelon', 'Watermelon'), ('cucumbers', 'Cucumbers'), ('squash', 'Squash/Zucchini'), ('peppers', 'Peppers'), ('tomatoes', 'Tomatoes'), ('strawberries', 'Strawberries'), ('vegetables', 'Mixed Vegetables'), ('orchard', 'Orchard/Fruit Trees'), ('other', 'Other')], max_length=50)),
                ('crop_type_other', models.CharField(blank=True, help_text="If 'Other', please specify", max_length=100)),
                ('acreage', models.DecimalField(decimal_places=2, help_text='Approximate acreage to be pollinated', max_digits=6)),
                ('num_hives_requested', models.PositiveIntegerField(blank=True, help_text="Number of hives requested (leave blank if unsure, we'll recommend)", null=True)),
                ('preferred_start_date', models.DateField(help_text='When do you need the bees?')),
                ('duration_weeks', models.PositiveIntegerField(default=4, help_text='How many weeks do you need pollination services?')),
                ('notes', models.TextField(blank=True, help_text='Any additional information about your pollination needs')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pollination Request',
                'verbose_name_plural': 'Pollination Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
