# Generated by Django 6.0 on 2026-01-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_beeremovalrequest_pollinationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeremovalrequest',
            name='prefer_callback',
            field=models.BooleanField(default=False, help_text='Customer prefers a phone callback'),
        ),
        migrations.AddField(
            model_name='nukerequest',
            name='prefer_callback',
            field=models.BooleanField(default=False, help_text='Customer prefers a phone callback'),
        ),
        migrations.AddField(
            model_name='order',
            name='prefer_callback',
            field=models.BooleanField(default=False, help_text='Customer prefers a phone callback'),
        ),
        migrations.AddField(
            model_name='pollinationrequest',
            name='prefer_callback',
            field=models.BooleanField(default=False, help_text='Customer prefers a phone callback'),
        ),
    ]
