# Generated by Django 6.0 on 2026-01-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_beeremovalrequest_prefer_callback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, help_text="Optional - for follow-up if we can't reach you by phone", max_length=254)),
                ('interest', models.CharField(choices=[('honey', 'Honey Products'), ('nucs', 'Bee Nucs (Starter Colonies)'), ('pollination', 'Pollination Services'), ('bee_removal', 'Bee Removal'), ('general', 'General Question'), ('other', 'Other')], default='general', help_text='What would you like to discuss?', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Any additional details (optional)')),
                ('best_time', models.CharField(blank=True, help_text='Best time to reach you (optional)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Callback Request',
                'verbose_name_plural': 'Callback Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
