# Generated by Django 6.0 on 2026-06-26 17:28

from django.db import migrations, models


# Describe jars by volume (Pint/Quart) instead of weight (16 oz/32 oz).
SIZE_RENAMES = {
    "16 oz": "Pint",
    "32 oz": "Quart",
}


def weights_to_volumes(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    for old, new in SIZE_RENAMES.items():
        Product.objects.filter(name="Wildflower Honey", size=old).update(size=new)


def volumes_to_weights(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    for old, new in SIZE_RENAMES.items():
        Product.objects.filter(name="Wildflower Honey", size=new).update(size=old)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(help_text='Jar volume, e.g., Pint, Quart, Gallon', max_length=100),
        ),
        migrations.RunPython(weights_to_volumes, volumes_to_weights),
    ]
