# Generated by Django 6.0 on 2026-06-26 18:37

from django.db import migrations, models


def retire_draft_orders(apps, schema_editor):
    # The order flow is now single-step, so 'draft' is gone. Any leftover drafts
    # from the old review/confirm flow were never confirmed — mark them cancelled.
    Order = apps.get_model("shop", "Order")
    Order.objects.filter(status="draft").update(status="cancelled")


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.RunPython(retire_draft_orders, migrations.RunPython.noop),
    ]
