# Generated by Django 6.0 on 2026-06-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_slackmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackmessage',
            name='bot_reaction',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
